const KEYBOARDS = {
    mainMenu: "Bosh menyu 🏠",
    cancel:"Bekor qilish",
    callTaxi:"Taksi chaqirish",
    pay: "Hisobni to'ldirish",
    toBeTaxi: "Taksi bo'lish",
    videoGuide: "Video qo'llanma",
    countUser:"Obunachilar soni",
    monthlyBenefit: "Oylik tushum",
    payToDrive: "Haydovchi balansini to'ldirish",
    addAdmin:"Admin qo'shish",
    sendMsg:"Habar yuborish",
    addOrder:"✅ Buyurtma berish",
    editOrder:"🖊 O'zgartirish",
    from: "🌎 Ketish joyi",
    to:"🌎 Boradigan joy",
    name:"🚹 Ism",
    carModel:"Mashina modeli",
    carNumber:"Mashina raqami",
    price:"💰 Narx",
    phoneNumber:"📱 Telefon raqam",
    yourPhoneNumber:"📱 Telefoningiz",
    editPrice: "Narxni o'zgartirish ♻️",
    accept: "Qabul qilish",
    confirm: "✅ Tasdiqlash",
    block:"Bloklash",
    unblock:"Blokdan chiqarish",
    inRegion:"Viloyat ichida",
    accrosRegion:"Viloyatlar aro"
}

export default KEYBOARDS